### ISSUE TITLE
Tar veldig lang tid å beregne `ArsakInnNy`

### ISSUE THREAD

**Issue by arnfinn** [Rapporteket/korona#6]
Gikk fra en halv time til to minutt når jeg deaktiverte følgende linje:
https://github.com/Rapporteket/korona/blob/f5de5bd71935fd7e21ab3f7ff0a8584880ad08e6/R/KoronaPreprossesser.R#L204

`Aarsak` er en `dplyr::case_when`-funksjon:
https://github.com/Rapporteket/korona/blob/f5de5bd71935fd7e21ab3f7ff0a8584880ad08e6/R/KoronaPreprossesser.R#L151-L159

Mulig det har noe med [PR 6300 i `dplyr`](https://www.github.com/tidyverse/dplyr/pull/6300) å gjøre?

**Comment by arnfinn** [comment]
Mulig samme som denne: https://www.github.com/tidyverse/dplyr/issues/6674

**Comment by lenaringstado** [comment]
Ja, det ble mye bedre i dplyr 1.1.1. Skal vurdere enklere aggregering av variabelen.
